### PR TITLE
Update Localization.json

### PR DESCRIPTION
**Pull request by LettereUniche**
Added Italian support.

### CODE REVIEW

**Comment by Arkhorse** [comment]
Technically the gas can is a jug or just a container. But its for sure not a tank. I didnt really check the loc when I took over the mod. Let me verify the English first

**Comment by Arkhorse** [comment]
Ok, have a look at 68931fdfbc552308e2a1253e45a1f1f0168c853f

**Comment by LettereUniche** [comment]
Alright then. Updated the italian localization based on the corrected english one.

**Comment by Arkhorse** [comment]
And I completely forgot about this AGAIN... Merging it in now and will release with the next one

**Pull request merged**
